require: rubocop-rspec

AllCops:
  Include:
    - 'lib/**/*'
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    # It is too heavy with math and formulae
    - 'lib/geo/coord/globes.rb'
    - 'spec/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'tmp/*'
    - '*.gemspec'
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.4

Layout/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

# To add its_* methods
Style/BlockDelimiters:
  ProceduralMethods:
  - benchmark
  - bm
  - bmbm
  - create
  - each_with_object
  - measure
  - new
  - realtime
  - tap
  - with_object
  FunctionalMethods:
  - let
  - let!
  - subject
  - watch
  IgnoredMethods:
  - lambda
  - proc
  - it
  - its
  - its_call
  - its_map
  AllowBracesOnProceduralOneLiners: false
  BracesRequiredMethods: []

Naming/AsciiIdentifiers:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "{}"
    "%i": "[]"

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 14

Gemspec/OrderedDependencies:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/ImplicitBlockExpectation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/FilePath:
  Enabled: false

RSpec:
  Language:
    Includes:
      Examples:
        - its
        - its_call
        - its_map
