name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    name: >-
      ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.5, 2.6, 2.7, 3.0 ]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: install dependencies
        run:  bundle install --jobs 3 --retry 3
      - name: spec
        run:  bundle exec rake spec
      - name: rubocop
        run:  bundle exec rake rubocop
